import Layout from "@/src/layouts/Layout";
import fonts from "@/src/utils/fonts";
import "./globals.scss";

export const metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
  icons: { icon: "/images/app-logo.png" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
